### ISSUE TITLE
Getting `OverlappingFileLockException` for Windows in Github actions

### ISSUE THREAD

**Issue by PriyanshC** [coursier/coursier#3267]
Proof of concept [repository](https://github.com/PriyanshC/coursier-windows-bug)

First noticed in [our project](https://github.com/j-mie6/parsley-debug-app) where we worked around it with manually removing files, enforcing UTF-8 encoding, always running `sbt clean` and setting a different tempdir

```yml
      - name: Clean SBT caches and set env (Windows only)
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          rm -rf "$GITHUB_WORKSPACE/.coursier-cache"
          rm -rf "C:/Users/runneradmin/.ivy2/cache"
          rm -rf "C:/Users/runneradmin/.sbt"
          echo "SBT_OPTS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          
      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Update sbt
        shell: bash
        run: |
          sbt clean
          sbt -Djava.io.tmpdir=$RUNNER_TEMP update


```
